steps:
- name: 'golang:1.20'
  args: ['go', 'mod', 'download', 'github.com/casbin/casbin/v2']
- name: 'golang:1.20'
  args: ['go', 'build', '-o', 'app']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-west1-docker.pkg.dev/silver-tape-392620/astrafydocker/astrafygov1:${SHORT_SHA}', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-west1-docker.pkg.dev/silver-tape-392620/astrafydocker/astrafygov1:${SHORT_SHA}']
options:
  logging: CLOUD_LOGGING_ONLY
