apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-astrafy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-astrafy
  template:
    metadata:
      labels:
        app: go-astrafy
    spec:
      containers:
        - name: go-astrafy
          image: ${{ env.IMAGE_URL }}
          ports:
            - containerPort: 8080